repository_type: pipeline
lint:
  files_exist:
    # Our pipeline name doesn't have nf-core in it, so the logo doesn't either
    - assets/nf-core-yavsap_logo_light.png
    - docs/images/nf-core-yavsap_logo_light.png
    - docs/images/nf-core-yavsap_logo_dark.png
    # We don't have 'full' test data yet
    - conf/test_full.config
    # We don't use igenomes
    - conf/igenomes.config
    # We hang on to our Markdownlint config file for VSCode to read
    - .markdownlint.yml
  nextflow_config: false
  # Currently not supported, but hopefully soon!
  # See https://github.com/nf-core/tools/issues/1031
  # - mainfest.name
  # - manifest.homePage
  files_unchanged:
    - .markdownlint.yml
    - CODE_OF_CONDUCT.md
    - LICENSE
    - .github/CONTRIBUTING.md
    - .github/ISSUE_TEMPLATE/config.yml
    - .github/ISSUE_TEMPLATE/bug_report.yml
    - .github/ISSUE_TEMPLATE/feature_request.yml
    - .github/PULL_REQUEST_TEMPLATE.md
    - .github/workflows/branch.yml
    - .github/workflows/linting_comment.yml
    - .github/workflows/linting.yml
    - assets/email_template.html
    - assets/email_template.txt
    - assets/sendmail_template.txt
    - .gitignore
    - .gitattributes
    - docs/README.md
    - assets/multiqc_config.yaml
    - .prettierrc.yml
  actions_ci:
    false
    # Can't find minimum NF version and doesn't like the addition of 'dispatch'
    # to the events
  multiqc_config: false
