contact_links:
  - name: Join nf-core
    url: https://nf-co.re/join
    about: Please join the nf-core community here
  - name: "Slack #yavsap channel"
    url: https://nfcore.slack.com/channels/yavsap
    about: Discussion about the nf-core/yavsap pipeline
