name: Testing
# This workflow runs the pipeline with the minimal test dataset to check that it completes without any syntax errors
on:
  push:
    branches:
      - develop
  pull_request:
  release:
    types: [published]
  workflow_dispatch:

env:
  NXF_ANSI_LOG: false
  CAPSULE_LOG: none

jobs:
  test:
    name: Run workflow tests
    # Only run on push if this is the develop branch (merged PRs)
    if: ${{ github.event_name != 'push' || (github.event_name == 'push' && github.repository == 'ksumngs/yavsap') }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Nextflow versions
        include:
          # Test pipeline minimum Nextflow version
          - NXF_VER: "21.10.6"
            NXF_EDGE: ""
          - NXF_VER: ""
            NXF_EDGE: "1"
    steps:
      - name: Check out pipeline code
        uses: actions/checkout@v2

      - name: Install Nextflow
        env:
          NXF_VER: ${{ matrix.NXF_VER }}
          # Uncomment only if the edge release is more recent than the latest stable release
          # See https://github.com/nextflow-io/nextflow/issues/2467
          # NXF_EDGE: ${{ matrix.NXF_EDGE }}
        run: |
          wget -qO- get.nextflow.io | bash
          sudo mv nextflow /usr/local/bin

      - name: Run pipeline with test data
        env:
          NCBI_API_KEY: ${{ secrets.NCBI_API_KEY }}
        run: |
          nextflow run ${GITHUB_WORKSPACE} -profile test,gh,docker

  parameters:
    name: Test workflow parameters
    if: ${{ github.event_name != 'push' || (github.event_name == 'push' && github.repository == 'ksumngs/yavsap') }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        parameters:
          - "--keep_taxid classified"
          - "--kraken2_db https://genome-idx.s3.amazonaws.com/kraken/16S_Silva132_20200326.tgz --keep_taxid unclassified"
          - "--kraken2_db ~/kraken2-db"
          - "--skip_qc"
          - "--skip_trimming"
          - "--skip_filtering"
          - "--skip_haplotype"
          - "--skip_phylogenetics"
    steps:
      - name: Check out pipeline code
        uses: actions/checkout@v2

      - name: Install Nextflow
        run: |
          wget -qO- get.nextflow.io | bash
          sudo mv nextflow /usr/local/bin

      - name: Download Kraken2 database
        if: ${{ matrix.parameters == '--kraken2_db ~/kraken2-db' }}
        run: |
          mkdir ~/kraken2-db
          wget -qO- https://genome-idx.s3.amazonaws.com/kraken/k2_viral_20210517.tar.gz | tar xzv -C ~/kraken2-db

      - name: Run pipeline with test data
        env:
          NCBI_API_KEY: ${{ secrets.NCBI_API_KEY }}
        run: |
          nextflow run ${GITHUB_WORKSPACE} -profile test,gh,docker ${{ matrix.parameters }}

  test_interleaved:
    name: Test Interleaved Reads Workflow
    # Only run on push if this is the develop branch (merged PRs)
    if: ${{ github.event_name != 'push' || (github.event_name == 'push' && github.repository == 'ksumngs/yavsap') }}
    runs-on: ubuntu-latest
    steps:
      - name: Check out pipeline code
        uses: actions/checkout@v2

      - name: Install Nextflow
        run: |
          wget -qO- get.nextflow.io | bash
          sudo mv nextflow /usr/local/bin

      - name: Run pipeline with test data
        env:
          NCBI_API_KEY: ${{ secrets.NCBI_API_KEY }}
        run: |
          nextflow run ${GITHUB_WORKSPACE} -profile test_interleaved,gh,docker
  test_nanopore:
    name: Run workflow tests
    # Only run on push if this is the develop branch (merged PRs)
    if: ${{ github.event_name != 'push' || (github.event_name == 'push' && github.repository == 'ksumngs/yavsap') }}
    runs-on: ubuntu-latest
    steps:
      - name: Check out pipeline code
        uses: actions/checkout@v2

      - name: Install Nextflow
        run: |
          wget -qO- get.nextflow.io | bash
          sudo mv nextflow /usr/local/bin

      - name: Run pipeline with test data
        env:
          NCBI_API_KEY: ${{ secrets.NCBI_API_KEY }}
        run: |
          nextflow run ${GITHUB_WORKSPACE} -profile test,gh,docker
