name: Testing
# This workflow runs the pipeline with the minimal test dataset to check that it completes without any syntax errors
on:
  - release
  - workflow_dispatch

jobs:
  test:
    name: Run workflow tests
    runs-on: ubuntu-latest
    continue-on-error: true
    env:
      NXF_VER: ${{ matrix.nxf_ver }}
      NXF_EDGE: ${{ matrix.nxf_edge }}
      NXF_ANSI_LOG: false
    strategy:
      matrix:
        # Nextflow versions: check pipeline minimum and current latest
        nxf_ver: ['21.04.3', '']
        nxf_edge: ['', '1']
    steps:
      - name: Check out pipeline code
        uses: actions/checkout@v2

      - name: Get a kraken database
        run: |
          mkdir kraken2db
          wget -qO- https://genome-idx.s3.amazonaws.com/kraken/k2_viral_20210517.tar.gz | tar xzv -C kraken2db

      - name: Install Nextflow
        env:
          CAPSULE_LOG: none
        run: |
          export NXF_VER
          export NXF_EDGE
          echo $NXF_VER $NXF_EDGE
          wget -qO- get.nextflow.io | bash
          sudo mv nextflow /usr/local/bin/

      - name: Run pipeline with test data
        env:
          NCBI_API_KEY: ${{ secrets.NCBI_API_KEY }}
        # TODO nf-core: You can customise CI pipeline run tests as required
        # For example: adding multiple test runs with different parameters
        # Remember that you can parallelise this by using strategy.matrix
        run: |
          nextflow run ${GITHUB_WORKSPACE} -profile test,docker
